version: "3.7"
services:
  core:
      image: hetao29/ipquery:latest
    ports:
      # HOST:CONTAINER
      - 8002:8000
    configs:
       - source: conf_v2
         target: /centrifugo/config.json
    command: centrifugo -c config.json
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    networks:
        - network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
networks:
    network:
        name: com_mxiqi_network
        external: true
configs:
    conf_v2:
      file: ./config.v2.json
